[tool.poetry]
name = "st_recruitment_svc"
version = "1.0.0"
description = ""
authors = ["ThesenAI"]
readme = "README.md"
packages = [{include = "st_recruitment_svc", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.1"
alembic = "^1.14.0"
sqlalchemy = "^2.0.36"
pydantic = "^2.10.2"
fastapi = "^0.115.5"
uvicorn = "^0.32.1"
httpx = "^0.28.1"
bcrypt = "^5.0.0"
pyjwt = "^2.11.0"
apscheduler = "^3.11.2"
python-multipart = "^0.0.22"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
apscheduler = "^3.11.2"

[tool.poetry.scripts]
st_recruitment_svc = "st_recruitment_svc.main:main"

[tool.pytest.ini_options]
pythonpath = [ "src/" ]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"